fix ci shell

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -69,7 +69,7 @@ jobs:
       - name: Build container
         run: |
           docker build \
-            --file Dockerfile \
+            --file "Dockerfile" \
             --build-arg PLATFORM="${{ matrix.platform }}" \
             --build-arg ENABLE_VALGRIND="1" \
             --build-arg ENABLE_CLANG="1" \
@@ -313,8 +313,8 @@ jobs:
       - name: Build container
         run: |
           docker build \
-            --file Dockerfile.alpine \
-            --tag cli \
+            --file "Dockerfile.alpine" \
+            --tag "cli" \
             .
       - name: Build CLI in container
         run: |
@@ -322,7 +322,7 @@ jobs:
             --rm \
             --volume "${PWD}:/workspace" \
             --workdir "/workspace" \
-            cli \
+            "cli" \
             /bin/sh -c '
               set -e;
               cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXE_LINKER_FLAGS="-static" -DCOLOPRESSO_USE_CLI=ON -DCOLOPRESSO_USE_TESTS=ON && \
@@ -342,12 +342,12 @@ jobs:
             alpine:latest \
             /bin/sh -c '
               /colopresso --verbose --format=pngx /assets/increase.png /tmp/increase.png; EXIT_CODE=$?; \
-              if test ${EXIT_CODE} -ne 2; then echo "Error: Expected exit code 2, got ${EXIT_CODE}"; exit 1; fi \
-              set -e;
+              if test ${EXIT_CODE} -ne 2; then echo "Error: Expected exit code 2, got ${EXIT_CODE}"; exit 1; fi; \
+              set -e; \
               /colopresso --version && \
               /colopresso --verbose --format=webp /assets/example.png /tmp/example.webp && \
               /colopresso --verbose --format=avif /assets/example.png /tmp/example.avif && \
-              /colopresso --verbose --format=pngx /assets/example.png /tmp/example.png && \
+              /colopresso --verbose --format=pngx /assets/example.png /tmp/example.png
             ' && \
           docker run \
             --rm \
@@ -356,10 +356,10 @@ jobs:
             busybox:musl \
             /bin/sh -c '
               /colopresso --verbose --format=pngx /assets/increase.png /tmp/increase.png; EXIT_CODE=$?; \
-              if test ${EXIT_CODE} -ne 2; then echo "Error: Expected exit code 2, got ${EXIT_CODE}"; exit 1; fi
-              set -e;
+              if test ${EXIT_CODE} -ne 2; then echo "Error: Expected exit code 2, got ${EXIT_CODE}"; exit 1; fi; \
+              set -e; \
               /colopresso --version && \
               /colopresso --verbose --format=webp /assets/example.png /tmp/example.webp && \
               /colopresso --verbose --format=avif /assets/example.png /tmp/example.avif && \
-              /colopresso --verbose --format=pngx /assets/example.png /tmp/example.png && \
+              /colopresso --verbose --format=pngx /assets/example.png /tmp/example.png
             '
